name: CI

on:
  push:
  pull_request:
    branches: [dependabot/**]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install pNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.26.3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - name: Install Packages
        run: pnpm install

      - name: Build
        run: pnpm run build
